import { ConnectButton } from "@rainbow-me/rainbowkit";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex h-screen w-full text-center">
          <div className="justify-center content-center align-middle m-auto">
            <h1 className="text-3xl underline my-2">
              Admin dashboard skeleton setup
            </h1>
            <ConnectButton />
          </div>
        </div>
      </main>
    </>
  );
}
