import { Tab, TabProps } from "@/components/Tab"
import Text from "@/components/Text"
import Head from "next/head"

export default function Home() {
  const tabs: TabProps = {
    contracts: {
      header: "Contracts",
      content: (
        <div>
          Contracts
          <div className="flex h-full w-full text-center">
            <div className="justify-center content-center align-middle m-auto">
              <Text>Contracts</Text>
            </div>
          </div>
        </div>
      ),
    },
    secondItem: {
      header: "Second Item",
      content: <div>Second Item</div>,
    },
  }
  return (
    <div>
      <Head>
        <title>Admin dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Tab tabs={tabs} />
      </main>
    </div>
  )
}
